import 'package:flutter/material.dart';

import '../../../core/theme/app_colors.dart';
import '../data/home_api_service.dart';
import '../domain/feature_item.dart';
import 'widgets/accessibility_score_card.dart';
import 'widgets/action_buttons_section.dart';
import 'widgets/features_checklist_card.dart';
import 'widgets/live_fix_log_card.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final HomeApiService _api = HomeApiService();

  final List<FeatureItem> _features = [
    const FeatureItem(name: 'Smart Contrast Fix'),
    const FeatureItem(name: 'Keyboard Navigation'),
    const FeatureItem(name: 'Dyslexia Font Mode'),
    const FeatureItem(name: 'Text-to-Speech'),
    const FeatureItem(name: 'AI Image Descriptions'),
  ];

  bool _isBusy = false;
  String _logMessage = 'Ready to apply accessibility enhancements';
  bool _isErrorLog = false;

  @override
  void initState() {
    super.initState();
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    try {
      final settings = await _api.fetchSettings();
      final rawFeatures = settings?['features'];
      if (rawFeatures is! Map<String, dynamic>) {
        return;
      }

      setState(() {
        _features[0] = _features[0].copyWith(
          enabled: rawFeatures['contrastFixer'] == true,
        );
        _features[1] = _features[1].copyWith(
          enabled: rawFeatures['globalMode'] == true,
        );
        _features[2] = _features[2].copyWith(
          enabled: rawFeatures['dyslexiaMode'] == true,
        );
        _features[3] = _features[3].copyWith(
          enabled: rawFeatures['tts'] == true,
        );
        _features[4] = _features[4].copyWith(
          enabled: rawFeatures['imageLabeling'] == true,
        );
      });
    } catch (_) {
      // Initial load failures should not block local interaction.
    }
  }

  void _toggleFeature(int index, bool value) {
    setState(() {
      _features[index] = _features[index].copyWith(enabled: value);
    });
  }

  void _resetSelections() {
    setState(() {
      for (var i = 0; i < _features.length; i++) {
        _features[i] = _features[i].copyWith(enabled: false);
      }
      _logMessage = 'All feature selections were reset locally';
      _isErrorLog = false;
    });
  }

  Map<String, bool> _settingsFeaturePayload() => {
    'globalMode': _features[1].enabled,
    'tts': _features[3].enabled,
    'stt': false,
    'contrastFixer': _features[0].enabled,
    'imageLabeling': _features[4].enabled,
    'dyslexiaMode': _features[2].enabled,
  };

  Future<void> _applyChanges() async {
    setState(() {
      _isBusy = true;
      _logMessage = 'Applying selected settings...';
      _isErrorLog = false;
    });

    try {
      await _api.saveSettings(
        profile: 'Default',
        features: _settingsFeaturePayload(),
      );
      if (!mounted) return;

      setState(() {
        _logMessage = 'Settings synced with backend successfully';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Changes applied successfully.')),
      );
    } catch (error) {
      if (!mounted) return;
      setState(() {
        _logMessage = error.toString();
        _isErrorLog = true;
      });
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Apply failed: $error')));
    } finally {
      if (!mounted) return;
      setState(() {
        _isBusy = false;
      });
    }
  }

  Future<void> _voiceControl() async {
    await _runVoiceAction(
      'Voice control mode enabled. Listening for your command.',
      'Voice control mode acknowledged by AI service',
    );
  }

  Future<void> _readPage() async {
    await _runVoiceAction(
      'Accessibility scan is complete. Focus mode and high contrast are available.',
      'Read page text generated by AI service',
    );
  }

  Future<void> _runVoiceAction(String prompt, String successMessage) async {
    setState(() {
      _isBusy = true;
      _logMessage = 'Contacting AI service...';
      _isErrorLog = false;
    });

    try {
      final result = await _api.requestReadAloud(prompt);
      if (!mounted) return;

      setState(() {
        _logMessage = '$successMessage: $result';
      });
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('AI action completed.')));
    } catch (error) {
      if (!mounted) return;
      setState(() {
        _logMessage = error.toString();
        _isErrorLog = true;
      });
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('AI action failed: $error')));
    } finally {
      if (!mounted) return;
      setState(() {
        _isBusy = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        centerTitle: false,
        title: const Text(
          'NeuroAccess',
          style: TextStyle(color: AppColors.title, fontWeight: FontWeight.w700),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const AccessibilityScoreCard(),
              const SizedBox(height: 16),
              const Text(
                'Features',
                style: TextStyle(
                  color: AppColors.title,
                  fontWeight: FontWeight.w700,
                  fontSize: 20,
                ),
              ),
              const SizedBox(height: 8),
              FeaturesChecklistCard(
                features: _features,
                onFeatureChanged: (event) =>
                    _toggleFeature(event.index, event.value),
              ),
              const SizedBox(height: 16),
              const Text(
                'Live Fix Log',
                style: TextStyle(
                  color: AppColors.title,
                  fontWeight: FontWeight.w700,
                  fontSize: 20,
                ),
              ),
              const SizedBox(height: 8),
              LiveFixLogCard(message: _logMessage, isError: _isErrorLog),
              const SizedBox(height: 16),
              ActionButtonsSection(
                onApply: _applyChanges,
                onReset: _resetSelections,
                onVoiceControl: _voiceControl,
                onReadPage: _readPage,
                isBusy: _isBusy,
              ),
              const SizedBox(height: 16),
              const Center(
                child: Text(
                  'Privacy-first • Runs locally',
                  style: TextStyle(color: AppColors.footer, fontSize: 15),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
